### ISSUE TITLE
Adaptive_Theme on windows has problem with shared_preferences

### ISSUE THREAD

**Issue by ThraaxSession** [BirjuVachhani/adaptive_theme#38]
**Describe the bug**
I try to use adaptive_theme first time with **windows** and ran into following issue:

**To Reproduce**
1. add adaptive_theme to project in version ^3.0.0
2. run the app with windows as target.

**Expected behavior**
The app starts up without error.

**Screenshots**
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:shared_preferences/shared_preferences.dart': Failed assertion: line 169 pos 14: 'key.startsWith(_prefix)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:169:14)
<asynchronous suspension>
#3      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:33:13)
<asynchronous suspension>
#4      ThemePreferences.fromPrefs (package:adaptive_theme/src/adaptive_theme_preferences.dart:62:21)
<asynchronous suspension>
#5      AdaptiveTheme.getThemeMode (package:adaptive_theme/src/adaptive_theme.dart:91:13)
<asynchronous suspension>
==> #6      main (package:spaceup_ui/main.dart:18:26) <==
<asynchronous suspension>
```

That's following line in my code
![image](https://user-images.githubusercontent.com/3085830/174271265-669f365f-ead6-4132-a811-43e672abc6c4.png)

I also use **shared_prefences_settings**. Might this be an issue? On Linux, Android and web there is no issue.

**Comment by BirjuVachhani** [comment]
@ThraaxSession That's weird. I do not have a windows machine to try this out right now! Try running example app on windows.

**Comment by ThraaxSession** [comment]
So, the plain example does work on windows. I still assume adaptive_theme does not work well with another dependency.
![image](https://user-images.githubusercontent.com/3085830/174836586-7a0be1ab-59d7-405d-8890-104219e83b4e.png)

**Comment by BirjuVachhani** [comment]
Hmm...I'll check with `shared_prefences_settings` dependency.

**Comment by BirjuVachhani** [comment]
@ThraaxSession I tried to use `shared_prefences_settings` with `adaptive_theme`'s example app but I am running into this! How are you able to use it with `adaptive_theme: ^3.0.0`? 

```
Running "flutter pub get" in example...                         
Because shared_preferences_settings >=1.2.0 depends on shared_preferences ^0.5.6+3 and every version of adaptive_theme from path depends on shared_preferences ^2.0.1, shared_preferences_settings >=1.2.0 is incompatible with adaptive_theme from path.
So, because example depends on both adaptive_theme from path and shared_preferences_settings ^1.2.0, version solving failed.
pub get failed (1; So, because example depends on both adaptive_theme from path and shared_preferences_settings ^1.2.0, version solving failed.)
```

**Comment by ThraaxSession** [comment]
Ok that is weird. I assume I might still have something cached on windows. I'll figure it out at weekend and let you know. 🙄

**Comment by BirjuVachhani** [comment]
Closing this issue because of inactivity. Feel free to re-open if you're still facing the issue.
